version : "3"
services:
  web:
    image: nginx # 존재하는 nginx 이미지를 사용한다.
    container_name: nginx # Nginx Container 이름 지정
    ports:
      - 80:80
    volumes:
      - /etc/nginx/:/etc/nginx # EC2 Nginx와 Docker Nginx Container를 매핑한다.


  spring1:
    build: . #Dockerfile 실행
    image: spring # 내가 만든 이미지 이름을 지정
    container_name: green
    ports:
      - 8080:8080
    volumes:
      - ./:/root/ # 필요 없을 수도 있지만 일단..
    environment:
      active: green


  spring2:
    build: . #Dockerfile 실행
    image: spring # 내가 만든 이미지 이름을 지정
    container_name: blue
    ports:
      - 8081:8080
    volumes:
      - ./:/root/ # 필요 없을 수도 있지만 일단..
    environment:
      active: blue
