spring:
  datasource:
    master:
      hikari:
        username: user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC


    slave:
      hikari:
        username: user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/db?serverTimezone=UTC

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

     
server:
  port: 80